version: '3.8'

services:
  om1_video_processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1_video_processor:latest
    container_name: om1_video_processor
    restart: unless-stopped
    network_mode: host
    privileged: true
    runtime: nvidia
    shm_size: "8g"
    environment:
      - CAMERA_INDEX=${CAMERA_INDEX:-/dev/video0}
      - MICROPHONE_INDEX=${MICROPHONE_INDEX:-default_mic_aec}
      - MIC_RNNOISE_MODEL_PATH=${MIC_RNNOISE_MODEL_PATH:-/app/om1_video_processor/models/rnnoise.rnnn}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/root/.config
      - OM_API_KEY_ID=${OM_API_KEY_ID}
      - OM_API_KEY=${OM_API_KEY}
      - GALLERY_DIR=/data/gallery
      - EMBEDS_DIR=/data/embeds
    volumes:
      - /dev/snd:/dev/snd:rw
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:rw
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:ro
      - ./.venv:/app/om1_video_processor/.venv
      - ./data/gallery:/data/gallery:rw
      - ./data/embeds:/data/embeds:rw
    devices:
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    group_add:
      - audio
