version: '3.8'

services:
  om1_video_processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1_video_processor:latest
    container_name: om1_video_processor
    restart: unless-stopped
    network_mode: host
    privileged: true
    runtime: nvidia
    shm_size: "4g"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/root/.config
      - OM_API_KEY_ID=${OM_API_KEY_ID}
      - OM_API_KEY=${OM_API_KEY}
      - CAMERA_INDEX=${CAMERA_INDEX:-/dev/video6}
      - MICROPHONE_INDEX=${MICROPHONE_INDEX:-hw:3,0}
    volumes:
      - /dev/snd:/dev/snd:rw
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:rw
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:ro
      - ./.venv:/app/om1_video_processor/.venv
    devices:
      - /dev/snd:/dev/snd
      - /dev/video6:/dev/video6
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    group_add:
      - audio
