[project]
name = "om1-video-processor"
version = "1.0.0"
description = "OM Video Processor"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "om1-modules @ git+https://github.com/OpenMind/om1-modules.git@e24426ff251bb72a0e12cd6c1f517d1cc896ac56",
]
